"""Synthetic experts with controllable error rate and error *correlation*.

All experts know the exact solver. Errors are injected in one of three modes:

  iid            (Theorem 3 of Zhang et al. 2024, plus a correlation knob)
      Per state, total error rate `rho`. A fraction `pi` of that error budget is
      *shared*: on "bias states" (deterministic hash of the position, h < beta = pi*rho)
      every expert plays the same deterministic wrong move. On the remaining states
      each expert independently errs with prob rho_r = (rho-beta)/(1-beta), choosing a
      uniformly random *non-optimal* legal move.
        pi = 0  -> all errors idiosyncratic  (denoisable by low temperature)
        pi = 1  -> all errors shared          (argmax of the mixture is wrong on bias states)
      Prediction: accuracy(tau->0) ~= 1 - pi*rho ; expert accuracy = 1 - rho.

  complementary  (Theorem 4). K experts; the position space is hashed into K regions;
      expert i is optimal in region i and uniformly random over legal moves elsewhere.

  selection      (skill selection, Abreu et al. 2025, with a sharp predicted threshold).
      K experts, K hashed regions. Expert i is optimal in region i and plays the *shared*
      wrong move (same for every non-expert) elsewhere: errors outside expertise are fully
      correlated, so plain denoising cannot fix them. Routing knob `alpha`: in a state of
      region j the move is generated by expert j with prob alpha + (1-alpha)/K, by another
      expert otherwise (alpha=0 uniform routing, alpha=1 perfect routing).
      Mixture mass on the optimal move = alpha + (1-alpha)/K, on the shared wrong move =
      (1-alpha)(K-1)/K, so the tau->0 imitator transcends iff alpha > (K-2)/(2K-2)  (K=4: 1/3).

  rule           (learnable shared bias). On every ply with ply % rule_mod == 0 all experts play the
      leftmost legal column (an error whenever it is not optimal). Elsewhere: iid random error
      with prob rho. Unlike the hash-based bias states of `iid`, this bias is a simple function
      of the move sequence, so a finite model *can* learn it. Prediction: tau->0 reproduces the
      rule exactly (acc on rule plies = P(leftmost legal is optimal)) and denoises the rest.

  composition    (skill composition across demonstrators with disjoint support — the gap named
      in Zhang et al. Sec. 4). Two expert families, each game played by one family on both sides:
        A (prob frac_a): optimal for ply < n_open, and the transcript is TRUNCATED at ply n_open
          (no endgame data, no result token).
        B (prob 1-frac_a): opening quality q_open for ply < n_open (optimal with prob q_open, else a
          uniformly random legal move), optimal for ply >= n_open.
      So endgame competence is demonstrated only on states reached from q-quality openings, and
      optimal openings lead to endgame states that appear in no transcript. Question: does the
      imitator play the endgame well after *its own* (optimal) openings? q_open=1 is the control.

  blind          (shared bias localised in the opening). Every expert is optimal except
      that it never plays the centre column during the first `blind_plies` plies.
      Optional extra iid noise `rho`.

Optimality is defined by the *outcome class* (win/draw/loss) of the resulting position,
i.e. the same reward we evaluate the imitator on.
"""
from __future__ import annotations

import hashlib
from dataclasses import dataclass, asdict, field

import numpy as np

from .game import W, Board
from .solver import INVALID, outcome_reward

ERR_NONE, ERR_RANDOM, ERR_SHARED = 0, 1, 2


def hash01(key: str, seed: int) -> float:
    h = hashlib.blake2b(f"{seed}|{key}".encode(), digest_size=8).digest()
    return int.from_bytes(h, "little") / 2**64


@dataclass
class ExpertConfig:
    mode: str = "iid"          # iid | complementary | selection | rule | composition | blind
    rho: float = 0.3           # total error rate per visited state (iid / blind extra noise)
    pi: float = 0.0            # fraction of error budget that is shared (iid only)
    k: int = 4                 # number of experts (complementary / selection)
    alpha: float = 0.0         # routing strength (selection only)
    blind_plies: int = 4       # (blind only)
    rule_mod: int = 3          # (rule only) every ply divisible by rule_mod is a rule ply
    q_open: float = 1.0        # (composition) opening quality of family B
    n_open: int = 8            # (composition) plies of the opening / truncation point of family A
    frac_a: float = 0.5        # (composition) fraction of games played by family A
    bias_seed: int = 12345     # seed of the shared hash (must be common to all experts)

    def to_dict(self):
        return asdict(self)

    @staticmethod
    def from_dict(d):
        return ExpertConfig(**{k: v for k, v in d.items() if k in ExpertConfig.__dataclass_fields__})

    def n_experts(self) -> int:
        return self.k if self.mode in ("complementary", "selection") else 1

    def tag(self) -> str:
        if self.mode == "iid":
            return f"iid_rho{self.rho}_pi{self.pi}"
        if self.mode == "complementary":
            return f"comp_k{self.k}"
        if self.mode == "selection":
            return f"sel_k{self.k}_a{self.alpha}"
        if self.mode == "rule":
            return f"rule_mod{self.rule_mod}_left_rho{self.rho}"
        if self.mode == "composition":
            return f"comp_q{self.q_open}_n{self.n_open}_fa{self.frac_a}"
        return f"blind_p{self.blind_plies}_rho{self.rho}"


def split_moves(scores: tuple[int, ...]):
    """-> (legal cols, optimal cols, non-optimal legal cols) under the outcome-class reward."""
    legal = [c for c in range(W) if scores[c] != INVALID]
    best = max(outcome_reward(scores[c]) for c in legal)
    opt = [c for c in legal if outcome_reward(scores[c]) == best]
    nonopt = [c for c in legal if outcome_reward(scores[c]) != best]
    return legal, opt, nonopt


class Experts:
    """Sampling + analytic move distributions for a given ExpertConfig."""

    def __init__(self, cfg: ExpertConfig):
        self.cfg = cfg
        beta = cfg.pi * cfg.rho if cfg.mode == "iid" else 0.0
        self.beta = beta
        self.rho_r = (cfg.rho - beta) / (1.0 - beta) if beta < 1 else 0.0

    # --- shared structures -------------------------------------------------
    def is_bias_state(self, board: Board) -> bool:
        return self.cfg.mode == "iid" and self.beta > 0 and hash01(board.board_key(), self.cfg.bias_seed) < self.beta

    def shared_wrong_move(self, board: Board, nonopt: list[int]) -> int:
        u = hash01(board.board_key(), self.cfg.bias_seed + 1)
        return nonopt[min(int(u * len(nonopt)), len(nonopt) - 1)]

    def region(self, board: Board) -> int:
        return min(int(hash01(board.board_key(), self.cfg.bias_seed + 2) * self.cfg.k), self.cfg.k - 1)

    def alpha_threshold(self) -> float:
        k = self.cfg.k
        return (k - 2) / (2 * k - 2)

    def mixture_weights(self, board: Board) -> np.ndarray:
        """g(i|x): probability that expert i generated the move at this state."""
        k = self.cfg.n_experts()
        w = np.full(k, 1.0 / k)
        if self.cfg.mode == "selection":
            a = self.cfg.alpha
            w = np.full(k, (1 - a) / k)
            w[self.region(board)] += a
        return w

    def sample_mover(self, board: Board, rng: np.random.Generator) -> int:
        """Which expert generates the next move (selection mode routing)."""
        if self.cfg.mode != "selection":
            return 0
        return int(rng.choice(self.cfg.k, p=self.mixture_weights(board)))

    # --- sampling -------------------------------------------------------------
    def sample_move(self, board: Board, scores, rng: np.random.Generator, expert_id: int = 0):
        """-> (col, err_flag, is_bias_state)."""
        legal, opt, nonopt = split_moves(scores)
        cfg = self.cfg
        if cfg.mode == "iid":
            if nonopt and self.is_bias_state(board):
                return self.shared_wrong_move(board, nonopt), ERR_SHARED, True
            if nonopt and rng.random() < self.rho_r:
                return int(rng.choice(nonopt)), ERR_RANDOM, False
            return int(rng.choice(opt)), ERR_NONE, False

        if cfg.mode == "complementary":
            if self.region(board) == expert_id:
                return int(rng.choice(opt)), ERR_NONE, False
            c = int(rng.choice(legal))
            return c, (ERR_RANDOM if c in nonopt else ERR_NONE), False

        if cfg.mode == "selection":
            if self.region(board) == expert_id or not nonopt:
                return int(rng.choice(opt)), ERR_NONE, bool(nonopt)
            return self.shared_wrong_move(board, nonopt), ERR_SHARED, True

        if cfg.mode == "rule":
            if board.n_moves % cfg.rule_mod == 0:
                c = legal[0]
                return c, (ERR_SHARED if c in nonopt else ERR_NONE), True
            if nonopt and rng.random() < cfg.rho:
                return int(rng.choice(nonopt)), ERR_RANDOM, False
            return int(rng.choice(opt)), ERR_NONE, False

        if cfg.mode == "composition":
            # expert_id: 0 = family A, 1 = family B
            if expert_id == 1 and board.n_moves < cfg.n_open and rng.random() >= cfg.q_open:
                c = int(rng.choice(legal))
                return c, (ERR_RANDOM if c in nonopt else ERR_NONE), True
            return int(rng.choice(opt)), ERR_NONE, board.n_moves < cfg.n_open

        if cfg.mode == "blind":
            if board.n_moves < cfg.blind_plies:
                cand_opt = [c for c in opt if c != W // 2]
                cand_non = [c for c in nonopt if c != W // 2]
                if cand_opt:
                    return int(rng.choice(cand_opt)), ERR_NONE, True
                if cand_non:
                    return int(rng.choice(cand_non)), ERR_SHARED, True
                return int(rng.choice(opt)), ERR_NONE, True
            if nonopt and rng.random() < cfg.rho:
                return int(rng.choice(nonopt)), ERR_RANDOM, False
            return int(rng.choice(opt)), ERR_NONE, False
        raise ValueError(cfg.mode)

    # --- analytic distributions (for evaluation) ----------------------------
    def dists(self, board: Board, scores) -> np.ndarray:
        """(n_experts, 7) move distribution of every expert at this state."""
        legal, opt, nonopt = split_moves(scores)
        cfg = self.cfg
        n = self.cfg.n_experts()
        out = np.zeros((n, W))
        if cfg.mode == "iid":
            if nonopt and self.is_bias_state(board):
                out[0, self.shared_wrong_move(board, nonopt)] = 1.0
            else:
                pr = self.rho_r if nonopt else 0.0
                out[0, opt] = (1 - pr) / len(opt)
                if nonopt:
                    out[0, nonopt] = pr / len(nonopt)
        elif cfg.mode == "complementary":
            r = self.region(board)
            for i in range(n):
                if i == r:
                    out[i, opt] = 1.0 / len(opt)
                else:
                    out[i, legal] = 1.0 / len(legal)
        elif cfg.mode == "selection":
            r = self.region(board)
            for i in range(n):
                if i == r or not nonopt:
                    out[i, opt] = 1.0 / len(opt)
                else:
                    out[i, self.shared_wrong_move(board, nonopt)] = 1.0
        elif cfg.mode == "rule":
            if board.n_moves % cfg.rule_mod == 0:
                out[0, legal[0]] = 1.0
            else:
                pr = cfg.rho if nonopt else 0.0
                out[0, opt] = (1 - pr) / len(opt)
                if nonopt:
                    out[0, nonopt] = pr / len(nonopt)
        elif cfg.mode == "composition":
            # analytic baseline = family B's policy (the only family defined on the whole game)
            if board.n_moves < cfg.n_open:
                out[0, opt] += cfg.q_open / len(opt)
                out[0, legal] += (1 - cfg.q_open) / len(legal)
            else:
                out[0, opt] = 1.0 / len(opt)
        elif cfg.mode == "blind":
            if board.n_moves < cfg.blind_plies:
                cand_opt = [c for c in opt if c != W // 2]
                cand_non = [c for c in nonopt if c != W // 2]
                cand = cand_opt or cand_non or opt
                out[0, cand] = 1.0 / len(cand)
            else:
                pr = cfg.rho if nonopt else 0.0
                out[0, opt] = (1 - pr) / len(opt)
                if nonopt:
                    out[0, nonopt] = pr / len(nonopt)
        return out
