"""Write RESULTS.md: one table per experiment family from results/<tag>/seed*/states.json + matches.

  python -m c4.report --results results --out RESULTS.md
"""
from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from pathlib import Path

import numpy as np


def fmt(vals, pct=True, pm=True):
    v = np.array([x for x in vals if x is not None], dtype=float)
    if v.size == 0:
        return "–"
    m = v.mean() * (100 if pct else 1)
    if v.size > 1 and pm:
        return f"{m:.1f} ± {v.std() * (100 if pct else 1):.1f}"
    return f"{m:.1f}" if pct else f"{m:.3f}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="results"); ap.add_argument("--out", default="RESULTS.md")
    ap.add_argument("--narrative", default="NARRATIVE.md", help="markdown file prepended to the tables (if it exists)")
    a = ap.parse_args()
    R = Path(a.results)
    by_tag = defaultdict(list)
    for p in sorted(R.glob("*/seed*/states.json")):
        d = json.loads(p.read_text())
        m = {}
        for mp in p.parent.glob("match_expert_t*.json"):
            m[mp.stem.split("_t")[-1]] = json.loads(mp.read_text())
        d["_match"] = m; d["_seed"] = p.parent.name
        by_tag[p.parents[1].name].append(d)
    if not by_tag:
        Path(a.out).write_text("# Results\n\nNo results yet.\n"); return

    L = ["# Results", "", "All numbers are on held-out states generated by the same experts (fresh seed).",
         "`acc` = probability mass the imitator puts on an optimal move (exact, from logits). `E[r]` = expected reward (win 1, draw 0.5, loss 0, illegal 0).",
         "`best expert` = the best single expert's expected reward on the same states. **Transcendence** = imitator E[r] > best expert.",
         "Match score = (wins + 0.5 draws)/games of the imitator against an expert bot, alternating colours, 5 retries on illegal output.", ""]

    def tmin(d):
        return str(min(float(t) for t in d["taus"]))

    # --- iid family --------------------------------------------------------------
    iid = {t: ds for t, ds in by_tag.items() if re.fullmatch(r"iid_rho[\d.]+_pi[\d.]+", t)}
    if iid:
        L += ["## H1–H3, H5: error correlation π at fixed error rate ρ (denoising)", "",
              "Prediction: acc(τ→0) ≈ 1 − shared-error rate; gain over the expert ≈ realized random-error rate; on bias states acc(τ→0) ≈ 0.", "",
              "| π | seeds | expert acc | acc τ=1 | acc τ→0 | **theory acc τ→0** | E[r] τ→0 − best expert | acc τ→0 bias states | bias states by phase (open/mid/late) | acc τ→0 non-bias | match τ→0 | match τ=1 |",
              "|---|---|---|---|---|---|---|---|---|---|---|---|"]
        for tag in sorted(iid, key=lambda t: float(re.search(r"pi([\d.]+)", t).group(1))):
            ds = iid[tag]; pi = re.search(r"pi([\d.]+)", tag).group(1); t0 = tmin(ds[0])
            bph = "/".join(fmt([d["taus"][t0].get("acc_bias_by_phase", [None]*3)[k] for d in ds]) for k in range(3))
            L.append("| {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} |".format(
                pi, len(ds), fmt([d["expert"]["acc"] for d in ds]), fmt([d["taus"]["1.0"]["acc"] for d in ds]),
                fmt([d["taus"][t0]["acc"] for d in ds]), fmt([d["theory"]["acc_tau0"] for d in ds]),
                fmt([d["taus"][t0]["gain_vs_best_expert"] for d in ds]),
                fmt([d["taus"][t0]["acc_bias"] for d in ds]), bph, fmt([d["taus"][t0]["acc_nonbias"] for d in ds]),
                fmt([d["_match"].get("0.001", {}).get("score") for d in ds]), fmt([d["_match"].get("1.0", {}).get("score") for d in ds])))
        L.append("")

    # --- selection family ---------------------------------------------------------
    sel = {t: ds for t, ds in by_tag.items() if re.fullmatch(r"sel_k\d+_a[\d.]+", t)}
    if sel:
        thr = sel[next(iter(sel))][0]["theory"]["alpha_threshold"]
        L += ["## Skill selection: routing strength α with fully shared errors outside expertise", "",
              f"Prediction: τ→0 transcends the best expert iff α > α* = {thr:.3f}. Mixture mass on optimal = α + (1−α)/K.", "",
              "| α | predicted | seeds | best expert acc | mixture acc | acc τ=1 | acc τ→0 | E[r] τ→0 − best expert | transcends? | match τ→0 | match τ=1 |",
              "|---|---|---|---|---|---|---|---|---|---|---|"]
        for tag in sorted(sel, key=lambda t: float(re.search(r"_a([\d.]+)", t).group(1))):
            ds = sel[tag]; al = re.search(r"_a([\d.]+)", tag).group(1); t0 = tmin(ds[0])
            L.append("| {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} |".format(
                al, "yes" if ds[0]["theory"]["transcends_predicted"] else "no", len(ds),
                fmt([d["expert"]["best_acc"] for d in ds]), fmt([d["expert"]["mixture_acc"] for d in ds]),
                fmt([d["taus"]["1.0"]["acc"] for d in ds]), fmt([d["taus"][t0]["acc"] for d in ds]),
                fmt([d["taus"][t0]["gain_vs_best_expert"] for d in ds]),
                "/".join("yes" if d["taus"][t0]["transcends_best_expert"] else "no" for d in ds),
                fmt([d["_match"].get("0.001", {}).get("score") for d in ds]), fmt([d["_match"].get("1.0", {}).get("score") for d in ds])))
        L.append("")

    # --- others ---------------------------------------------------------------------
    oth = {t: ds for t, ds in by_tag.items() if t not in iid and t not in sel}
    if oth:
        L += ["## Other conditions", "", "| condition | seeds | best expert acc | mixture acc | acc τ=1 | acc τ→0 | E[r] τ→0 − best expert | acc τ→0 bias states (expert acc on same states) | bias by phase (open/mid/late) | match τ→0 |",
              "|---|---|---|---|---|---|---|---|---|---|"]
        for tag, ds in sorted(oth.items()):
            t0 = tmin(ds[0])
            bph = "/".join(fmt([d["taus"][t0].get("acc_bias_by_phase", [None]*3)[k] for d in ds]) for k in range(3))
            def exp_acc_bias(d):
                ab, nb = d["expert"].get("acc_bias_by_phase"), d["expert"].get("n_bias_by_phase")
                if not ab or not nb or sum(nb) == 0:
                    return None
                return sum(a * n for a, n in zip(ab, nb) if a is not None) / sum(nb)
            eb = fmt([exp_acc_bias(d) for d in ds])
            L.append("| {} | {} | {} | {} | {} | {} | {} | {} | {} | {} |".format(
                tag, len(ds), fmt([d["expert"]["best_acc"] for d in ds]), fmt([d["expert"]["mixture_acc"] for d in ds]),
                fmt([d["taus"]["1.0"]["acc"] for d in ds]), fmt([d["taus"][t0]["acc"] for d in ds]),
                fmt([d["taus"][t0]["gain_vs_best_expert"] for d in ds]), fmt([d["taus"][t0]["acc_bias"] for d in ds]) + " (" + eb + ")", bph,
                fmt([d["_match"].get("0.001", {}).get("score") for d in ds])))
        L.append("")

    # --- sanity ------------------------------------------------------------------------
    L += ["## Sanity checks", "", "| condition | states evaluated | mass on non-move tokens (τ=1) | mass on illegal columns (τ=1) | favor: frac states with abs ΔE[r] < 0.01 | favor: frac > +0.1 | favor: frac < −0.1 |",
          "|---|---|---|---|---|---|---|"]
    for tag, ds in sorted(by_tag.items()):
        d = ds[0]; f = d["favor"][tmin(d)]
        L.append(f"| {tag} | {d['n_states']} | {fmt([d['mass_on_nonmove_tokens_tau1']])} | {fmt([d['mass_on_illegal_cols_tau1']])} | {fmt([f['frac_abs_lt_0.01']])} | {fmt([f['frac_gt_0.1']])} | {fmt([f['frac_lt_-0.1']])} |")
    L += ["", "## Figures", "", "![reward vs tau](results/figs/fig1_reward_vs_tau.png)", "![gain vs pi](results/figs/fig2_gain_vs_pi.png)",
          "![selection](results/figs/fig6_selection_alpha.png)", "![bias vs nonbias](results/figs/fig3_bias_vs_nonbias.png)",
          "![favor](results/figs/fig4_favor.png)", "![training](results/figs/fig5_training.png)", ""]
    head = Path(a.narrative).read_text() + "\n" if Path(a.narrative).exists() else ""
    Path(a.out).write_text(head + "\n".join(L))
    print("wrote", a.out)


if __name__ == "__main__":
    main()
